### ISSUE TITLE
Start with Item/Image association

### ISSUE THREAD

**Issue by bethlakshmi** [bethlakshmi/abc-inventory#12]
I think this can be reasonably sized, and yet impactful.

Let the user looking at the item list associate images with items.  
This can be 1 of two ways:

1. By picking already uploaded images (via a bulk import - now available in Admin pages, someday available through the same navigation as the list)

1. By uploading some more images - can be multiple files.

The user is allowed to do 1 or both.

Flow:

1. User picks the images icon from the list for the item that wants more/different images.

1. User gets the list of current images and can un-select any of them

1. User also gets a list of "available" images - ie, images not attached to any other item (limiting options somewhat to help with navigation)

1. User can also choose to upload more images

After adding/removing/uploading images, the user chooses to save their choices.  Any newly uploaded images are attached to that image.

**Comment by bethlakshmi** [comment]
First crack is done and uploaded on:  

https://abc-inventory-stage.us.aldryn.io/inventory/item/list

What you should see:

- on the far right, there's now two images that are actions - the edit button, and an image button ("Manage Images").
- you click the new Manage Images button, and you get a new screen with:
     - all of the thumbnails of current images uploaded already.  The images that are associated with this item are highlighted with a blue border.  You can link more images by clicking on them.  The click is an on/off toggle.
     - a file upload button for adding more images from your computer/external drive.  This is a multi-select, you can upload as many files as you like.
     - Cancel/submit button... it does the obvious.
- when you pick some images and/or upload some images the tool then:
     - saves an image file (if this is an upload)
     - links the image to the item
     - unlinks any images that you chose NOT to attach to the item anymore (if they were linked to the item previously) - but it does NOT delete the image itself.
     - returns you to the list of items (images now shown) and reports what item was just edited, and how many images are now linked/uploaded.
     - highlights the changed item in green

I will probably do a few more improvements:

- help text to tell you you can do multi-file uploads
- hover to show the file name of the uploaded image and may be other details.
- test cases

Let me know what you think --- I'm worried that showing every thumbnail ever is going to get bothersome... but I'm willing to handle that in another ticket as I don't think it's a problem yet.

**Comment by burlexpo** [comment]
_I'm worried that showing every thumbnail ever is going to get bothersome... but I'm willing to handle that in another ticket as I don't think it's a problem yet._

I agree.

BTW, in your email you said to reply here rather than emailing.  I only emailed **back** to you.  If you create a ticket here and tag me in, I always reply here.

**Comment by bethlakshmi** [comment]
I said that because I know I'm changing the norms on Mina.  I've been trying to be user friendly on getting out updates and trying to hold back on the nerdiness of GitHub... but it's getting bothersome, since I use this as the process w. you on burl-expo.  Just wanted to make an announcement and try to get us all doing this.
