### ISSUE TITLE
Add photos within workflow?

### ISSUE THREAD

**Issue by burlexpo** [bethlakshmi/abc-inventory#31]
Right now in order to add images, I have to create an item, save the item, return to the main menu, search for the item, click on the "edit image" button, and then add the images.

It would be super if adding images was integrated into the workflow so that -- from the users POV -- when you click save on what is currently the last screen, you get taken to the image upload thing.

**Comment by bethlakshmi** [comment]
exactly the same as the current edit image screen, but at the end of the flow.  Got it.

**Comment by bethlakshmi** [comment]
fixed on live
