### ISSUE TITLE
Sorting/Identifying/managing images

### ISSUE THREAD

**Issue by burlexpo** [bethlakshmi/abc-inventory#33]
Currently, https://abc-inventory.us.aldryn.io/inventory/item/images/16 shows a big ol' pile of images.  It would be great if they were sorted or tagged in some way.  Or -- at least -- that the images associated with the item you clicked on were physically separated from the mass of images (I know they're highlighted).

Also, there doesn't seem to be a good way for a user to unlink an image from an item or to remove duplicate images (we have some). Yes, I can do it through /admin

**Comment by bethlakshmi** [comment]
So... plan could be:
1 - list of currently selected images that are highlighted are separate and a section at top of page
2 - on ALL images - provide a deletion mechanism (like an X on the image or a trashcan)
3 - But KEEP all images (even ones linked to something else) on the page.  Separate into 3 groups (linked to this, images that are not linked, images that ARE linked to something else).  With the upload more at the bottom.

Keep the image linky icon, though.

**Comment by bethlakshmi** [comment]
Deployed on live
