### ISSUE TITLE
Last edited by

### ISSUE THREAD

**Issue by burlexpo** [bethlakshmi/abc-inventory#41]
Can we track the last person to edit an inventory item and have it display on the card? I don't need it to display in the columns, but it would be great if down at the bottom of the item it said something like

Last edited: MM/DD/YYYY by [User Name]

Also @bethlakshmi I don't seem to be able to add assignees or labels. Weird.  Maybe it's Chrome. This would be an enhancement.

**Comment by bethlakshmi** [comment]
On it.  Should be doable.  
I use Chrome and I can do assignees and labels.  Weird.

**Comment by bethlakshmi** [comment]
Merged and updated on Live as of now.  Only tracks who updated an item going forward.
