### ISSUE TITLE
"notes" and "subject" fields do not import in bulk upload

### ISSUE THREAD

**Issue by burlexpo** [bethlakshmi/abc-inventory#43]
@bethlakshmi I thought it was me, but I uploaded the same files twice (after deleting the entries) and the Subject and Notes fields do not import at all.

**Comment by bethlakshmi** [comment]
Hmm... it could be I fixed the bug in my work at the same time?  But I can't reproduce this.  I just tried every field it currently supports and both subject and notes (and all the others) work.

You selected the column to be the value you wanted, right?

Please try one more time, if it doesn't work, mail me your file and I'll try it too.

**Comment by bethlakshmi** [comment]
@burlexpo  - can you retest this?  I can't replicate
