### ISSUE TITLE
Combining Tags

### ISSUE THREAD

**Issue by burlexpo** [bethlakshmi/abc-inventory#51]
@bethlakshmi 

1) Be able to select two or more tags (check boxes) and then push a COMBINE button (for example: Fans; Fan; Fan Dancer; Pig)
2) Display tags selected in prior screen, this time with radio buttons so only one can be selected.  The default is **no** radio button is selected.  Select one (example: Pig).  Push the COMBINE button or the CANCEL button.
2a) If no radio button is selected and user selects COMBINE, throw an error message saying "You must select one option".  
3) Get a pop-up warning: "Are you sure you want to combine all of these tags under [NAME]?" (I.e., Pig)
4) User clicks CONFIRM or CANCEL.  
5) If you click confirm, the tags "Fan", "Fans" and "Fan Dancer" would all be overwritten to be "Pig".

**Comment by bethlakshmi** [comment]
Woohoo!  I think I just got this right:

https://abc-inventory-stage.us.aldryn.io/

There's a lot of subtlety to this flow, so I would not mind a look before I expand on and test this.

Start at the "Tags" area - and you'll see checkboxes and a Merge button.

**Comment by bethlakshmi** [comment]
fixed and deployed
