### ISSUE TITLE
Make Column Display Preferences Persistent

### ISSUE THREAD

**Issue by burlexpo** [bethlakshmi/abc-inventory#52]
Tag @bethlakshmi so she sees this

A user is working on the main inventory screen.  They hide some columns and display others.  They create a new item.  They are returned to the main inventory screen.  The columns they hid are now visible again; the columns they displayed -- if they are hidden by default -- are hidden again.

It would be super if each user could set their own preferences, but at least having the preference persist across a session wouldn't be so annoying.

**Comment by bethlakshmi** [comment]
I see you found your power... :)

**Comment by bethlakshmi** [comment]
fixed and deployed
